### ISSUE TITLE
Swagger.ed icon does not show up in the address bar

### ISSUE THREAD

**Issue by gtinjr** [apispots/apispots-extension#1]
Using latest chrome browser, the swagger.ed icon is not showing up in the address bar when opening a local swagger 2.0 file from the hard drive.  The file was created with swagger editor and it contains valid 2.0 syntax.
The extension has Allow access to file URLs permissions checked.

Chrome Version 43.0.2357.65 (64-bit)
running on OSX Yosemite

**Comment by xrysanthos** [comment]
Hi @gtinjr!  Is it possible to send the file over and have a look for myself?

**Comment by gtinjr** [comment]
I sent it to your gmail account.  Thx

**Comment by xrysanthos** [comment]
Ok, two problems in this case - both related to the [Swagger v2 parser module](https://github.com/BigstickCarpet/swagger-parser).
- The parser throws an error when parsing the file, saying that there are some circular references detected in some of the models.  There is a config option to disable that - I've encountered this error many times so far and decided to disable it.  Unfortunately I'm not propagating any errors to the browser's console (yet) so there is no way to find this except from debugging it yourself
- The parser is not able to parse the file correctly when in local mode - i.e. file://.  The way to overcome this issue is to serve the swagger definition file from a web server.  What I normally do is use Python'
  s Simple HTTP server module which is great for launching a static web server on the fly:

> python -m SimpleHTTPServer

What I did was to disable the model reference resolution feature in the parser and released a new version of the plugin (v1.1.2).  I've just pushed it to the repo.  Download it and try to serve your resource through HTTP and you should be good to go.

I had a go myself and your API looks really nice on the graph ;)

**Comment by gtinjr** [comment]
Thanks!!! I will give it a try.

**Comment by gtinjr** [comment]
I can see the new release but there is no crx file to download.

**Comment by gtinjr** [comment]
Ok, I downloaded the zip file and I found the crx in a subfolder.  I will test it now.

**Comment by gtinjr** [comment]
It is working and it looks awesome.  Thanks a lot!!!
