### ISSUE TITLE
option to run this as a nodejs microservice?

### ISSUE THREAD

**Issue by tachtevrenidis** [apispots/apispots-extension#4]
can I somehow hardcode the swagger location uri in the code base and run this as a nodejs app (on aws or azure) instead of as a browser extension?

**Comment by xrysanthos** [comment]
Hi Kosta!  Well, since the tools are designed as SPA's and Swagger client supports enabling CORS mode it could be done but it would need some work I guess.  Although my goal is when the project reaches a maturity level to extract all modules under /lib as separate stand-alone lib projects that will work in both browser and Node environments, as far as the front-facing parts are concerned they will remain Chrome dependent.

**Comment by tachtevrenidis** [comment]
ok
